### ISSUE TITLE
Consider refactoring to use the ZSH plugin standard

### ISSUE THREAD

**Issue by unixorn** [Green0wl/zsh-git-kali-prompt#1]
There are more details in the [ZSH plugin standard](https://zdharma-continuum.github.io/Zsh-100-Commits-Club/Zsh-Plugin-Standard.html) docs, but the TLDR is that if you do some minor tweaks and name your theme with a `.plugin.zsh` suffix, people using plugin managers will be able to use the theme without manually editing their `.zshrc`.

**Comment by Green0wl** [comment]
Thank you very much for the suggestion! I'm sorry, but since I don't use plugin managers myself, there are no plans to edit an existing prompt for a plugin.

**Comment by Green0wl** [comment]
After some code review, I came to your conclusion that adding plugin support might be a good idea. Thanks! Added.

**Comment by unixorn** [comment]
Sorry it took so long to get this added - it's in today's update.

**Comment by Green0wl** [comment]
Thank you! I have added some comment to your commit.
